- name: Nginxをインストールするためのリポジトリを追加する
  apt_repository:
    repo: "ppa:nginx/stable"

- name: apt-get update
  apt:
    update_cache: yes

- name: Nginxをインストールする
  apt:
    name: nginx

- name: Nginxの設定ファイルを更新する
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Nginxを起動する
  service:
    name: nginx
    state: restarted
