- name: リポジトリを追加する
  apt_repository:
    repo: 'deb http://apt.mackerel.io/debian/ mackerel contrib'

- name: GPG keyをダウンロードする
  apt_key:
    url: https://mackerel.io/assets/files/GPG-KEY-mackerel

- name: apt-get update
  apt:
    update_cache: yes

- name: mackerel-agent をインストールする
  apt:
    pkg: mackerel-agent

- name: /etc/mackerel-agent/mackerel-agent.conf を作成する
  template:
    src:  mackerel-agent.conf
    dest: /etc/mackerel-agent/mackerel-agent.conf

- name: mackerel-agent を起動する
  command: /etc/init.d/mackerel-agent start
